const STATUS_CODE_OK = 200;
const STATUS_CODE_CREATED = 201;
const BAD_REQUEST = 400;

const INVALID_FIELDS = 'Invalid fields';


module.exports = {
  STATUS_CODE_OK,
  STATUS_CODE_CREATED,
  BAD_REQUEST,
  INVALID_FIELDS,
};